name: Mirror

on:
  push:
    branches: ["*"]
    tags: ["*"]

permissions:
  contents: read

jobs:
  sync:
    if: ${{ secrets.GITLAB_TOKEN != '' && secrets.CODEBERG_TOKEN != '' }}
    uses: nexnc/workflows/.github/workflows/mirror.yml@main
    secrets: inherit
